classDiagram
    class NewsPost {
        -String: identifier
        -Date: date
        -String: title
        -String: caption
        -Optional<Bool>: notify
        -Optional<String>: tintColor
        -Optional<URL>: url
        -Optional<URL>: imageURL
        -Optional<String>: appID
        -Optional<String>: sourceIdentifier
    }
