classDiagram
    class AppRelease {
        -String: name
        -String: bundleIdentifier
        -Optional<String>: subtitle
        -String: developerName
        -String: localizedDescription
        -Int: size
        -URL: downloadURL
        -String: sha256 (fairseal)
        -URL: iconURL
        -Array<URL>: screenshotURLs
        -String: version
        -Date: versionDate
        -Optional<String>: versionDescription
        -Optional<String>: tintColor
        -Optional<Bool>: beta
        -Optional<String>: sourceIdentifier
        -Optional<[String]>: categories
        -Optional<Int>: downloadCount
        -Optional<Int>: starCount
        -Optional<Int>: followerCount
        -Optional<Int>: forkCount
        -Optional<Int>: issueCount
        -Optional<Int>: openIssueCount
        -Optional<Int>: sourceSize
    }
