%%{init: { 'logLevel': 'debug', 'theme': 'forest' } }%%
sequenceDiagram
    %% see: https://mermaid-js.github.io/mermaid/#/sequenceDiagram
    Creator->>Platform: Fork: appfair/App
    Platform-->>Creator: fork created at:<br />github.com/App-Org/App.git
    activate Creator
    Note over Creator: App Development
    Note over Creator: App Testing
    Creator->>Platform: Integrate: Pull Request
    deactivate Creator
    Note over Platform: Validate Creator
    Note over Platform: Validate App
    Note over Platform: Build & Sign Binary
    Note over Platform: Release Artifacts
    Note over Platform: Update Catalog
    Consumer->>Platform: Browse & Search apps
    Platform-->>Consumer: app catalog
    Note over Consumer: Search Apps
    Note over Consumer: Compare Apps
    Note over Consumer: Select App
    Note over Consumer: Approve Permissions
    Consumer->>Platform: Install App
    Platform-->>Consumer: app download & install
    Note over Consumer: Use App

    rect rgb(0, 100, 200, 0.3)
        loop User-Developer Communication
            Consumer->>Creator: Consumer Feedback
                Note over Platform: Discussion Forums
                Note over Creator,Consumer: Direct Communication
                Note over Platform: Issue Reporting System
            Creator->>Consumer: Creator Response
        end
    end

    Note over Creator: Maintain App
    Note over Creator: Fix Bugs
    Note over Creator: Add Features
    Creator->>Platform: Integrate: Pull Request
    Note over Platform: Build & Release
    Note over Platform: Update Catalog
    Platform-->>Consumer: app update notification
    Note over Consumer: Review App Changes
    Note over Consumer: Choose to Update App
    Consumer->>Platform: Update App
    Platform-->>Consumer: app updated


