classDiagram
    class FairCatalog {
        -String: name
        -String: identifier
        -Array<AppRelease>: apps
        -Array<NewsPost>: news
    }

    class AppRelease {
        -String: name
        -String: bundleIdentifier
        -Optional<String>: subtitle
        -String: developerName
        -String: localizedDescription
        -Int: size
        -URL: downloadURL
        -URL: iconURL
        -Array<URL>: screenshotURLs
        -String: version
        -Date: versionDate
        -Optional<String>: versionDescription
        -Optional<String>: tintColor
        -Optional<Bool>: beta
        -Optional<String>: sourceIdentifier
    }

    class NewsPost {
        -String: identifier
        -Date: date
        -String: title
        -String: caption
        -Optional<Bool>: notify
        -Optional<String>: tintColor
        -Optional<URL>: url
        -Optional<URL>: imageURL
        -Optional<String>: appID
        -Optional<String>: sourceIdentifier
    }
