classDiagram
    class AppRelease {
        -String: name
        -String: bundleIdentifier
        -Optional<String>: subtitle
        -String: developerName
        -String: localizedDescription
        -Int: size
        -URL: downloadURL
        -URL: iconURL
        -Array<URL>: screenshotURLs
        -String: version
        -Date: versionDate
        -Optional<String>: versionDescription
        -Optional<String>: tintColor
        -Optional<Bool>: beta
        -Optional<String>: sourceIdentifier
    }
